version: "3.8"
name: "redwood-blog"

services:
  db:
    image: postgres
    container_name: redwood-blog-postgres
    restart: unless-stopped
    networks:
      - redwood-blog-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  media-server:
    build:
      context: ./docker
      dockerfile: Dockerfile.media-server
    container_name: redwood-blog-media-server
    restart: unless-stopped
    shm_size: 4g
    networks:
      - redwood-blog-network
    volumes:
      - media-server-config:/config
      - ./scripts/on-stream-event.sh:/scripts/on-stream-event.sh
      - ./certs/server.key:/server.key
      - ./certs/server.crt:/server.crt
    env_file:
      - .env
    ports:
      - 4242:4242 # API/UI
      - 1935:1935 # RTMP
      # - 8080:8080/tcp # HTTP
      - 4433:4433/tcp # HTTPS
      - 8889:8889/udp # SRT
      - 5554:5554 # RTSP

networks:
  redwood-blog-network:
    driver: bridge

volumes:
  pgdata:
  media-server-config:
