# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml
# You can customize graphql and dbauth urls individually too:
# see https://redwoodjs.com/docs/app-configuration-redwood-toml#api-paths

[web]
title = "Redwood App"
port = "${WEB_DEV_PORT:8910}"
apiUrl = "/.redwood/functions"
includeEnvironmentVariables = []

[api]
port = "${API_DEV_PORT:8911}"

[browser]
open = true

[notifications]
versionUpdates = ["latest"]
