# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml
# You can customize graphql and dbauth urls individually too:
# see https://redwoodjs.com/docs/app-configuration-redwood-toml#api-paths

[web]
title = "Blazing"
port = "${WEB_PORT:8910}"
host = "0.0.0.0"
apiUrl = "/api"
includeEnvironmentVariables = []

[api]
port = "${API_PORT:8911}"
host = "0.0.0.0"

[browser]
open = true

[notifications]
versionUpdates = ["latest"]

[studio.graphiql.authImpersonation]
authProvider = "dbAuth"
email = "ivansudevlop@gmail.com"
userId = "1"
roles = ["admin"]

[graphql]
fragments = true
