FROM alpine AS mist_build

RUN apk add --update git meson ninja gcc g++ linux-headers git

RUN git clone https://github.com/DDVTECH/mistserver.git
RUN cd mistserver && git checkout feature/alpine_docker_builds

RUN cp -r /mistserver /src
RUN mkdir /build/; cd /build; meson setup /src -DDEBUG=3 -Dstrip=true; ninja install

FROM alpine

COPY --from=mist_build /usr/local/ /usr/local/
RUN apk add libstdc++

ENTRYPOINT ["MistController"]
